modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Crimix/wrap-radial/issues"

[[mods]]
modId="realbedo"
version="${file.jarVersion}"
displayName="Re-Albedo"
updateJSONURL="https://raw.githubusercontent.com/Crimix/Re-Albedo/master/update.json"
# displayURL="https://www.curseforge.com/minecraft/mc-mods/re-albedo"
logoFile="warp-radial-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
authors="black_dog20"
description='''Continuing the legacy of Albedo'''

[[dependencies.realbedo]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.realbedo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.realbedo]]
    modId="realbedo"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="BEFORE"
    side="BOTH"
